name: Build Image and Run Example

on: [push, pull_request]

env:
  IP: 127.0.0.1

jobs:
  build:
    name: Build Images and Deploy Example WebApp
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build Infra Images
      run: |-
        ./build-docker-image.sh

    - name: Generate yaml and Start PanteraS
      run: |-
        ./generate_yml.sh && \
        docker-compose up -d

    - name: Build and Run Example WebApp
      run: |-
        cd examples/SmoothWebappPython && \
        ./build-docker-image.sh &&
        ./start_with_marathon.sh deploy0_marathon.json
